// File generated by FlutterFire Configuration based on google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrke0qJvqEaNcCWdCNNoUKminvfO1s0TM',
    appId: '1:415742364224:web:fc798f07bbd16580132da5',
    messagingSenderId: '415742364224',
    projectId: 'doctor-c7c29',
    authDomain: 'doctor-c7c29.firebaseapp.com',
    storageBucket: 'doctor-c7c29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrke0qJvqEaNcCWdCNNoUKminvfO1s0TM',
    appId: '1:415742364224:android:fc798f07bbd16580132da5',
    messagingSenderId: '415742364224',
    projectId: 'doctor-c7c29',
    storageBucket: 'doctor-c7c29.firebasestorage.app',
  );
}
