/**
 * Multi-Language Localization Dictionary
 * Healthcare Workforce Platform
 * Supports: English (en), Tamil (ta), Hindi (hi), Telugu (te), Malayalam (ml), Kannada (kn)
 */

class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'HealthForce',
      'languageName': 'English',
      'changeLanguage': 'Change Language',
      'selectLanguage': 'Select Preferred Language',
      'marketplace': 'Duty Marketplace',
      'applications': 'My Applications',
      'assignments': 'Confirmed Shift',
      'profile': 'Doctor Profile',
      'verificationCenter': 'Verification Center',
      'verificationStatus': 'Verification Status',
      'verified': 'Verified',
      'underReview': 'Under Review',
      'needsInformation': 'Needs Information',
      'hospitalOperations': 'Hospital Operations',
      'postDuty': 'Post Duty Requirement',
      'activeDuties': 'Active Duty Requirements',
      'reviewApplicants': 'Review Applicants',
      'selectDoctor': 'Select Doctor',
      'applyForDuty': 'Apply for Duty',
      'startShift': 'Start Shift (Check-In)',
      'completeShift': 'Mark Shift Completed',
      'paymentTerms': 'Agreed Payment Terms',
      'paymentAcknowledged': 'Payment Acknowledged',
      'settings': 'Settings & Security',
      'signOut': 'Sign Out',
      'openInMaps': 'Open in Google Maps',
      'runVerification': 'Run Hybrid Verification',
      'submittedCredentials': 'Submitted Credentials',
      'officialCredentials': 'Official Council Record',
      'comparisonOutcome': 'Comparison Result',
      'fastTrackApproved': 'Fast-Track Approved (Clear Match)',
      'sentToReviewer': 'Sent to Reviewer Queue (Mismatch/Exception)',
      'saveDraft': 'Save as Draft',
      'previewDuty': 'Preview Duty',
      'publishDuty': 'Validate & Publish Duty',
    },
    'ta': {
      'appName': 'ஹெல்த்போர்ஸ்',
      'languageName': 'தமிழ்',
      'changeLanguage': 'மொழியை மாற்றுக',
      'selectLanguage': 'விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'marketplace': 'பணி சந்தை',
      'applications': 'என் விண்ணப்பங்கள்',
      'assignments': 'உறுதிசெய்யப்பட்ட பணி',
      'profile': 'மருத்துவர் சுயவிவரம்',
      'verificationCenter': 'சரிபார்ப்பு மையம்',
      'verificationStatus': 'சரிபார்ப்பு நிலை',
      'verified': 'சரிபார்க்கப்பட்டது',
      'underReview': 'மதிப்பாய்வில் உள்ளது',
      'needsInformation': 'கூடுதல் தகவல் தேவை',
      'hospitalOperations': 'மருத்துவமனை செயல்பாடுகள்',
      'postDuty': 'புதிய பணி தேவை இடுகையிடுக',
      'activeDuties': 'செயலில் உள்ள பணி தேவைகள்',
      'reviewApplicants': 'விண்ணப்பதாரர்களை மதிப்பாய்வு செய்க',
      'selectDoctor': 'மருத்துவரை தேர்வு செய்',
      'applyForDuty': 'பணிக்கு விண்ணப்பிக்கவும்',
      'startShift': 'பணியை தொடங்கு (செக்-இன்)',
      'completeShift': 'பணி நிறைவுற்றது என குறிக்கவும்',
      'paymentTerms': 'ஒப்பந்த கட்டண விதிமுறைகள்',
      'paymentAcknowledged': 'கட்டணம் பெறப்பட்டது',
      'settings': 'அமைப்புகள் & பாதுகாப்பு',
      'signOut': 'வெளியேறு',
      'openInMaps': 'கூகிள் வரைபடத்தில் பார்க்க',
      'runVerification': 'தானியங்கி சரிபார்ப்பை இயக்கு',
      'submittedCredentials': 'சமர்ப்பிக்கப்பட்ட விவரங்கள்',
      'officialCredentials': 'அதிகாரப்பூர்வ கவுன்சில் பதிவு',
      'comparisonOutcome': 'ஒப்பீட்டு முடிவு',
      'fastTrackApproved': 'உடனடி ஒப்புதல் (முழுப் பொருத்தம்)',
      'sentToReviewer': 'மதிப்பாய்வாளர் ஆய்வுக்கு அனுப்பப்பட்டது',
      'saveDraft': 'வரைவாக சேமி',
      'previewDuty': 'பணியை முன்னோட்டமிடுக',
      'publishDuty': 'சரிபார்த்து வெளியிடவும்',
    },
    'hi': {
      'appName': 'हेल्थफोर्स',
      'languageName': 'हिन्दी',
      'changeLanguage': 'भाषा बदलें',
      'selectLanguage': 'पसंदीदा भाषा चुनें',
      'marketplace': 'ड्यूटी मार्केटप्लेस',
      'applications': 'मेरे आवेदन',
      'assignments': 'पुष्ट शिफ्ट',
      'profile': 'डॉक्टर प्रोफ़ाइल',
      'verificationCenter': 'सत्यापन केंद्र',
      'verificationStatus': 'सत्यापन स्थिति',
      'verified': 'सत्यापित',
      'underReview': 'समीक्षाधीन',
      'needsInformation': 'अतिरिक्त जानकारी आवश्यक',
      'hospitalOperations': 'अस्पताल संचालन',
      'postDuty': 'ड्यूटी पोस्ट करें',
      'activeDuties': 'सक्रिय ड्यूटी आवश्यकताएं',
      'reviewApplicants': 'आवेदकों की समीक्षा करें',
      'selectDoctor': 'डॉक्टर चुनें',
      'applyForDuty': 'ड्यूटी के लिए आवेदन करें',
      'startShift': 'शिफ्ट शुरू करें (चेक-इन)',
      'completeShift': 'शिफ्ट पूर्ण चिह्नित करें',
      'paymentTerms': 'सहमति भुगतान शर्तें',
      'paymentAcknowledged': 'भुगतान स्वीकार किया गया',
      'settings': 'सेटिंग्स और सुरक्षा',
      'signOut': 'साइन आउट',
      'openInMaps': 'गूगल मैप्स में खोलें',
      'runVerification': 'सत्यापन जांच चलाएं',
      'submittedCredentials': 'प्रस्तुत विवरण',
      'officialCredentials': 'आधिकारिक परिषद रिकॉर्ड',
      'comparisonOutcome': 'तुलना परिणाम',
      'fastTrackApproved': 'त्वरित स्वीकृत (सटीक मिलान)',
      'sentToReviewer': 'समीक्षक कतार में भेजा गया',
      'saveDraft': 'ड्राफ्ट सहेजें',
      'previewDuty': 'ड्यूटी पूर्वावलोकन',
      'publishDuty': 'सत्यापित करें और प्रकाशित करें',
    },
    'te': {
      'appName': 'హెల్త్‌ఫోర్స్',
      'languageName': 'తెలుగు',
      'changeLanguage': 'భాషను మార్చండి',
      'selectLanguage': 'ప్రాధాన్య భాషను ఎంచుకోండి',
      'marketplace': 'డ్యూటీ మార్కెట్‌ప్లేస్',
      'applications': 'నా దరఖాస్తులు',
      'assignments': 'నిర్ధారిత షిఫ్ట్',
      'profile': 'వైద్యుని ప్రొఫైల్',
      'verificationCenter': 'ధృవీకరణ కేంద్రం',
      'verificationStatus': 'ధృవీకరణ స్థితి',
      'verified': 'ధృవీకరించబడింది',
      'underReview': 'సమీక్షలో ఉంది',
      'needsInformation': 'సమాచారం అవసరం',
      'hospitalOperations': 'ఆసుపత్రి కార్యకలాపాలు',
      'postDuty': 'డ్యూటీని పోస్ట్ చేయండి',
      'activeDuties': 'యాక్టివ్ డ్యూటీలు',
      'reviewApplicants': 'దరఖాస్తుదారులను సమీక్షించండి',
      'selectDoctor': 'వైద్యుడిని ఎంచుకోండి',
      'applyForDuty': 'డ్యూటీకి దరఖాస్తు చేసుకోండి',
      'startShift': 'షిఫ్ట్ ప్రారంభించండి',
      'completeShift': 'షిఫ్ట్ పూర్తయినట్లు గుర్తించండి',
      'paymentTerms': 'చెల్లింపు నిబంధనలు',
      'paymentAcknowledged': 'చెల్లింపు నిర్ధారించబడింది',
      'settings': 'సెట్టింగ్‌లు',
      'signOut': 'సైన్ అవుట్',
      'openInMaps': 'గూగుల్ మ్యాప్స్‌లో తెరవండి',
      'runVerification': 'ధృవీకరణను అమలు చేయండి',
      'submittedCredentials': 'సమర్పించిన వివరాలు',
      'officialCredentials': 'అధికారిక కౌన్సిల్ రికార్డు',
      'comparisonOutcome': 'పోలిక ఫలితం',
      'fastTrackApproved': 'తక్షణ ఆమోదం',
      'sentToReviewer': 'సమీక్షకు పంపబడింది',
      'saveDraft': 'డ్రాఫ్ట్‌గా సేవ్ చేయండి',
      'previewDuty': 'ముందస్తు వీక్షణ',
      'publishDuty': 'ప్రచురించండి',
    },
    'ml': {
      'appName': 'ഹെൽത്ത്ഫോഴ്സ്',
      'languageName': 'മലയാളം',
      'changeLanguage': 'ഭാഷ മാറ്റുക',
      'selectLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'marketplace': 'ഡ്യൂട്ടി മാർക്കറ്റ്പ്ലെയ്സ്',
      'applications': 'എന്റെ അപേക്ഷകൾ',
      'assignments': 'സ്ഥിരീകരിച്ച ഷിഫ്റ്റ്',
      'profile': 'ഡോക്ടർ പ്രൊഫൈൽ',
      'verificationCenter': 'പരിശോധനാ കേന്ദ്രം',
      'verificationStatus': 'പരിശോധനാ നില',
      'verified': 'പരിശോധിച്ചുറപ്പിച്ചു',
      'underReview': 'പരിശോധനയിലാണ്',
      'needsInformation': 'കൂടുതൽ വിവരം ആവശ്യമാണ്',
      'hospitalOperations': 'ആശുപത്രി പ്രവർത്തനങ്ങൾ',
      'postDuty': 'ഡ്യൂട്ടി പോസ്റ്റ് ചെയ്യുക',
      'activeDuties': 'സജീവ ഡ്യൂട്ടികൾ',
      'reviewApplicants': 'അപേക്ഷകരെ പരിശോധിക്കുക',
      'selectDoctor': 'ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
      'applyForDuty': 'ഡ്യൂട്ടിക്ക് അപേക്ഷിക്കുക',
      'startShift': 'ഷിഫ്റ്റ് ആരംഭിക്കുക',
      'completeShift': 'ഷിഫ്റ്റ് പൂർത്തിയായി',
      'paymentTerms': 'വേതന വ്യവസ്ഥകൾ',
      'paymentAcknowledged': 'വേതനം ലഭിച്ചു',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'signOut': 'പുറത്തുകടക്കുക',
      'openInMaps': 'മാപ്പിൽ തുറക്കുക',
      'runVerification': 'പരിശോധന നടത്തുക',
      'submittedCredentials': 'നൽകിയ വിവരങ്ങൾ',
      'officialCredentials': 'ഔദ്യോഗിക രേഖകൾ',
      'comparisonOutcome': 'ഫലം',
      'fastTrackApproved': 'അംഗീകരിച്ചു',
      'sentToReviewer': 'പരിശോധനയ്ക്ക് അയച്ചു',
      'saveDraft': 'ഡ്രാഫ്റ്റ് സൂക്ഷിക്കുക',
      'previewDuty': 'പ്രിവ്യൂ',
      'publishDuty': 'പ്രസിദ്ധീകരിക്കുക',
    },
    'kn': {
      'appName': 'ಹೆಲ್ತ್‌ಫೋರ್ಸ್',
      'languageName': 'ಕನ್ನಡ',
      'changeLanguage': 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
      'selectLanguage': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'marketplace': 'ಡ್ಯೂಟಿ ಮಾರುಕಟ್ಟೆ',
      'applications': 'ನನ್ನ ಅರ್ಜಿಗಳು',
      'assignments': 'ದೃಢಪಡಿಸಿದ ಪಾಳಿ',
      'profile': 'ವೈದ್ಯರ ಪ್ರೊಫೈಲ್',
      'verificationCenter': 'ಪರಿಶೀಲನಾ ಕೇಂದ್ರ',
      'verificationStatus': 'ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'underReview': 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
      'needsInformation': 'ಮಾಹಿತಿ ಅಗತ್ಯವಿದೆ',
      'hospitalOperations': 'ಆಸ್ಪತ್ರೆ ಕಾರ್ಯಾಚರಣೆಗಳು',
      'postDuty': 'ಡ್ಯೂಟಿ ಪೋಸ್ಟ್ ಮಾಡಿ',
      'activeDuties': 'ಸಕ್ರಿಯ ಕರ್ತವ್ಯಗಳು',
      'reviewApplicants': 'ಅರ್ಜಿದಾರರನ್ನು ಪರಿಶೀಲಿಸಿ',
      'selectDoctor': 'ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'applyForDuty': 'ಡ್ಯೂಟಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'startShift': 'ಪಾಳಿ ಪ್ರಾರಂಭಿಸಿ',
      'completeShift': 'ಪಾಳಿ ಪೂರ್ಣಗೊಳಿಸಿ',
      'paymentTerms': 'ಪಾವತಿ ನಿಯಮಗಳು',
      'paymentAcknowledged': 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'signOut': 'ಸೈನ್ ಔಟ್',
      'openInMaps': 'ಮ್ಯಾಪ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
      'runVerification': 'ಪರಿಶೀಲನೆ ಚಲಾಯಿಸಿ',
      'submittedCredentials': 'ಸಲ್ಲಿಸಿದ ವಿವರಗಳು',
      'officialCredentials': 'ಅಧಿಕೃತ ದಾಖಲೆಗಳು',
      'comparisonOutcome': 'ಫಲಿತಾಂಶ',
      'fastTrackApproved': 'ತ್ವರಿತ ಅನುಮೋದನೆ',
      'sentToReviewer': 'ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
      'saveDraft': 'ಕರಡಾಗಿ ಉಳಿಸಿ',
      'previewDuty': 'ಮುನ್ನೋಟ',
      'publishDuty': 'ಪ್ರಕಟಿಸಿ',
    }
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ??
           _localizedValues['en']?[key] ??
           key;
  }
}
